# Starter Secret for HW3_C
# Replace <username> with your actual username
# Replace the placeholder values with your REAL per-student credentials
# (from your HW3_A+B handout CSV)
#
# These are read by the init container (MinIO creds) and the main container (Qdrant key).

apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: qbc12-hw03-c-arshia-ataei   # TODO: your namespace
type: Opaque
stringData:
  # From your handout CSV columns 5/6
  minio-access-key: "qbc12-arshia_ataei"          # TODO
  minio-secret-key: "656ae4cad40050c00911159f91f1940f83b5db2b30c419fb3fda9102c6234ead"  # TODO
  # From SHARED.txt (same for everyone)
  qdrant-api-key: "060463f273fed95e5c04db5313971e25c2aa82fd03e2aa3b959423a06ed2de08"     # TODO