apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RBMk1qUTVNVGN3SGhjTk1qWXdOakExTURJd01UVTNXaGNOTXpZd05qQXlNREl3TVRVMwpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RBMk1qUTVNVGN3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFTQ1RCTjRDdHRlZzM3c2V2YWhUQURMTHRvUWRFR25xdkwraGgzVENheUwKVEFPRGRTWjZiT2dWUjRMM2VwSlZibVIvbUh4S1Y2K04wRm5jdndnSWFUNHBvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFQQWVXdXY5Wkp4aXlXdnFzOFJEClN5Qm04VFF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnVDR4ejJmcC9UU0s2VXZvVTA0OUwvczFxY1c5aEYwM2IKMlhlUHNXOXFVOU1DSVFEZ1hpUmExM284ZndyYzNweVI4U2NGbG8vb0ZRdzAzTXhza3UyeXg0YmQ4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://185.50.38.163:6443
  name: qbc12-k3s
contexts:
- context:
    cluster: qbc12-k3s
    namespace: qbc12-hw03-c-arshia-ataei
    user: arshia_ataei
  name: arshia_ataei@qbc12-k3s
current-context: arshia_ataei@qbc12-k3s
kind: Config
preferences: {}
users:
- name: arshia_ataei
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ikw4WlhNcTk2WGhfRVcxOFc4QXJDd19wa21vWlpOajZLNDQ2djlDTEFyLXMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoyMDk1OTg2MzQzLCJpYXQiOjE3ODA2MjYzNDMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiZTYwMGEzYzAtYWFhOC00MzFhLWIxOTYtZGFiZmM2NDJjZWEzIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJxYmMxMi1odzAzLWMtYXJzaGlhLWF0YWVpIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6InN0dWRlbnQtc2EiLCJ1aWQiOiJlZmZjMmRmMi1mNWE3LTQ5MGMtOTdlZS1hOWFlNWEzZTVmMjUifX0sIm5iZiI6MTc4MDYyNjM0Mywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnFiYzEyLWh3MDMtYy1hcnNoaWEtYXRhZWk6c3R1ZGVudC1zYSJ9.rvJ90ljby_3zH0ePlHYpxauH1WOM3anKx3eGDjTGdAHPJTBEvy339j8m0CByHAobhzeBi8v_BewgFa6zEREq0htsznft1rlS1ne63QpwvyJmzEnH5ghAARp6puUwqLcx3yFheKOh6hRt7gZkkCiaqvuHdEAqUBVIFMZyHUvCGieu7XKWJ7RnH0sM_UDO6NI_TXq2-Xxi4R2J8xw33bKCS0Ze1j69KJA3bsl33bpFdAb-vFTnC-INqddtwqK_siYyFIYaT-CzEn8jnz609b0dQv4uXunouRX5kDcAvrvLMhJn_QDLC6Etf63wvYiCZxNW231zZhdy4shPRHqtO0jThg
